### GitHub Workflow for the Java-Taskbar-Examples repo

# Simple build and store artifact flow.

# This GitHub Actions workflow automates the build and packaging process.

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'

    - name: Build with Maven
      run: mvnw clean install

    - name: Run tests
      run: mvnw test

    - name: Package JAR
      run: mvnw package

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: taskbar-icon-app
        path: target/*.jar
